---
- hosts: zabbix
  tasks:
  - name: MySQL installation
    dnf:
      name:
        - mysql
        - mysql-server
      state: latest

  - name: Start MySQL
    shell: "systemctl start mysqld"

  - name: Ensure MySQL is Enabled
    service: name=mysqld state=started enabled=true

  - name: update mysql root password for all root accounts  
    mysql_user:  
      name: root  
      host: "{{ item }}"  
      password: "P@ssw0rd"  
      login_user: root  
      login_password: "P@ssw0rd"  
      check_implicit_admin: yes  
      priv: "*.*:ALL,GRANT"  
    with_items:  
      - "{{ ansible_hostname }}"  
      - 127.0.0.1  
      - ::1  
      - localhost

  - name: Removes all anonymous user accounts
    community.mysql.mysql_user:
      login_user: root  
      login_password: "P@ssw0rd"  
      name: ''
      host_all: true
      state: absent

  - name: Check Zabbix DB has already been Created
    ansible.builtin.stat:
      path: '/var/lib/mysql/zabbix'
    register: zabbix_db

  - name : Create Database zabbix
    mysql_db: name=zabbix state=present login_user=root login_password=P@ssw0rd
    when: not zabbix_db.stat.exists

  - name: Create User zabbix
    community.mysql.mysql_user:
      login_user: root  
      login_password: "P@ssw0rd"  
      name: zabbix
      host: "{{ item }}"  
      #password: 'zabbix'
      priv: 'zabbix.*:ALL,GRANT'
      state: present
    with_items:  
      - localhost

#  - name: Check Schema DB has already been Import
#    ansible.builtin.stat:
#      path: '/var/lib/mysql/zabbix/triggers.ibd'
#    register: screma_db

#  - name: Copy Schema to zabbix Host
#    copy: src=zabbix.sql dest=/tmp/zabbix.sql
#    when: not screma_db.stat.exists

  - name: Set read_only variable to 1 persistently
    community.mysql.mysql_variables:
      login_user: root  
      login_password: "P@ssw0rd" 
      variable: read_only
      value: 1
      mode: global
      #mode: persist


