---
- hosts: zabbix
  tasks:
  - name: Check Zabbix Repo has already been Installed
    ansible.builtin.stat:
      path: /etc/yum.repos.d/zabbix.repo
    register: zabbix_pkg

  - name: Install Zabbix repository
    shell: "rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm"
    when: not zabbix_pkg.stat.exists
      
  - name: zabbix installation
    dnf:
      name:
        - zabbix-server-mysql     
        - zabbix-agent
        - zabbix-apache-conf
        - zabbix-web-mysql
        - zabbix-selinux-policy
        - zabbix-sql-scripts
      state: latest

  - name: Check Schema DB has already been Import
    ansible.builtin.stat:
      path: '/var/lib/mysql/zabbix/triggers.ibd'
    register: screma_db

  - name: Import Schema to zabbix Database
    #ansible.builtin.shell:
    #  cmd: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p zabbix
    shell: "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p zabbix"
    when: not screma_db.stat.exists

  - name: Config Zabbix Database in zabbix_server.conf
    ansible.builtin.shell:
      cmd: sed -i '/# DBPassword=/c\DBPassword=zabbix' /etc/zabbix/zabbix_server.conf

  - name: Config Log file size in zabbix_server.conf
    ansible.builtin.shell:
      cmd: sed -i '/LogFileSize=0/c\LogFileSize=50' /etc/zabbix/zabbix_server.conf

  - name: Start Zabbix-Server
    shell: "systemctl start zabbix-server"

  - name: Ensure Zabbix-Server is Enabled
    service: name=zabbix-server state=started enabled=true

  - name: Start Zabbix-Agent
    shell: "systemctl start zabbix-agent"

  - name: Ensure Zabbix-Agent is Enabled
    service: name=zabbix-agent state=started enabled=true
