---
- hosts: all
  tasks:
  - name: Check Zabbix Repo has already been Installed
    ansible.builtin.stat:
      path: /etc/yum.repos.d/zabbix.repo
    register: zabbix_pkg

  - name: Install Zabbix repository
    shell: "rpm -Uvh https://repo.zabbix.com/zabbix/6.5/rhel/7/x86_64/zabbix-release-6.5-1.el7.noarch.rpm"
    when: not zabbix_pkg.stat.exists
      
  - name: zabbix installation
    yum:
      name:    
        - zabbix-agent
      state: latest

  - name: Config Zabbix Database in zabbix_server.conf
    ansible.builtin.shell:
      cmd: sed -i '/Server=/c\Server=192.168.10.165,192.168.10.166,192.168.10.167' /etc/zabbix/zabbix_agentd.conf

  - name: Config Zabbix Database in zabbix_server.conf
    ansible.builtin.shell:
      cmd: sed -i '/ServerActive=/c\ServerActive=192.168.10.165,192.168.10.166,192.168.10.167' /etc/zabbix/zabbix_agentd.conf

  - name: Config Log file size in zabbix_server.conf
    ansible.builtin.shell:
      cmd: sed -i '/LogFileSize=0/c\LogFileSize=50' /etc/zabbix/zabbix_agentd.conf

  - name: Start Zabbix-Agent
    shell: "systemctl start zabbix-agent"

  - name: Ensure Zabbix-Agent is Enabled
    service: name=zabbix-agent state=started enabled=true
