---
- hosts: zabbix
  tasks:
  - name: Check Zabbix Repo has already been Installed
    ansible.builtin.stat:
      path: /etc/yum.repos.d/zabbix.repo
    register: zabbix_pkg

  - name: Install Zabbix repository
    shell: "rpm -Uvh https://repo.zabbix.com/zabbix/6.5/rhel/7/x86_64/zabbix-release-6.5-1.el7.noarch.rpm"
    when: not zabbix_pkg.stat.exists
      
  - name: Zabbix-Agent installation
    yum:
      name:    
        - zabbix-agent
      state: latest

  - name: Template Zabbix-Agent config file
    copy:
      src: ./zabbix_agentd.conf
      dest: /etc/zabbix/

  - name: Start Zabbix-Agent
    shell: "systemctl restart zabbix-agent"

  - name: Ensure Zabbix-Agent is Enabled
    service: name=zabbix-agent state=started enabled=true
  
  - name: Allow Firewalld Port 10050,10051
    ansible.posix.firewalld:
      port : "{{ item }}/tcp"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 10050
      - 10051